import type { ChainConfig, ChainKey } from '../types';
const env = import.meta.env;
const source = 'contracts-v2/contracts-production/MegaCryptoLotteryV2ProductionCandidate.sol';
type Audit = Pick<ChainConfig['contracts'], 'deploymentStartBlock' | 'deploymentEvidence' | 'vrf'>;
const config = (key: ChainKey, chainId: number, name: string, nativeCurrency: string, explorer: string, defaults: string[], lottery: `0x${string}`, token: `0x${string}`, tokenDecimals: number, audit: Audit, status: ChainConfig['contracts']['status'] = 'verified', note?: string): ChainConfig => ({ key, chainId, name, nativeCurrency, explorer, rpcUrls: [env[`VITE_${key.toUpperCase()}_RPC_URL`], ...defaults].filter(Boolean), contracts: { lottery, token, tokenSymbol: 'USDT', tokenDecimals, status, source, note, ...audit } });
// Production V2 deployment registry. Contract identity is always chain ID + address.
export const CHAINS: Record<ChainKey, ChainConfig> = {
  polygon: config('polygon', 137, 'Polygon', 'POL', 'https://polygonscan.com', ['https://polygon-bor-rpc.publicnode.com', 'https://polygon-rpc.com'], '0x24e203eB34A5B095aB892cA1CBfD8B01F8D1Ec1e', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F', 6, { vrf: { status: 'verification-pending', note: 'Production V2 address configured. Runtime VRF and deployment-block audit is pending.' } }),
  bsc: config('bsc', 56, 'BNB Smart Chain', 'BNB', 'https://bscscan.com', ['https://bsc-dataseed.binance.org', 'https://bsc-rpc.publicnode.com'], '0x06778A545085f703bfaD5BfeCc619E7bc4F0Dd2D', '0x55d398326f99059fF775485246999027B3197955', 18, { vrf: { status: 'verification-pending', note: 'Production V2 address configured. The live round cutoff is read from the contract; no proposed schedule is assumed active.' } }),
  arbitrum: config('arbitrum', 42161, 'Arbitrum One', 'ETH', 'https://arbiscan.io', ['https://arb1.arbitrum.io/rpc', 'https://arbitrum-one-rpc.publicnode.com'], '0x91AaCA953ff5C12c69629bD2813b2e931f03e63C', '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9', 6, { vrf: { status: 'verification-pending', note: 'Production V2 address configured. Runtime VRF and deployment-block audit is pending.' } }),
  base: config('base', 8453, 'Base', 'ETH', 'https://basescan.org', ['https://mainnet.base.org', 'https://base-rpc.publicnode.com'], '0xBACd528df4c99ED77A8F143ca15cdB2795ac0D58', '0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2', 6, { vrf: { status: 'verification-pending', note: 'Production V2 address configured. Runtime VRF and deployment-block audit is pending.' } }),
  optimism: config('optimism', 10, 'Optimism', 'ETH', 'https://optimistic.etherscan.io', ['https://mainnet.optimism.io', 'https://optimism-rpc.publicnode.com'], '0xc6dA7Edc75995595dD82a941C0D7b559F8f5Aa98', '0x94b008aA00579c1307B0EF2c499aD98a8ce58e58', 6, { vrf: { status: 'verification-pending', note: 'Production V2 address configured. Runtime VRF and deployment-block audit is pending.' } }),
  avalanche: config('avalanche', 43114, 'Avalanche', 'AVAX', 'https://snowtrace.io', ['https://api.avax.network/ext/bc/C/rpc', 'https://avalanche-c-chain-rpc.publicnode.com'], '0x91AaCA953ff5C12c69629bD2813b2e931f03e63C', '0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7', 6, { vrf: { status: 'verification-pending', note: 'Production V2 address configured. Contract identity includes Avalanche chain ID; runtime VRF and deployment-block audit is pending.' } })
};
export const chainById = (id?: number) => Object.values(CHAINS).find(c => c.chainId === id);
