import { useEffect, useMemo, useState } from 'react';
import { CHAINS, chainById } from './config/chains';
import type { ChainKey, LotterySnapshot, WalletState } from './types';
import { NetworkGrid } from './components/NetworkGrid'; import { TransactionReview } from './components/TransactionReview'; import { Fairness } from './components/Fairness'; import { NumberPicker, normalizeTicketNumbers } from './components/NumberPicker'; import { GlobalPrizeDashboard } from './components/GlobalPrizeDashboard';
import { displayToken, readLottery } from './web3/lottery'; import { WalletController } from './web3/wallet'; import { friendlyError, prepareTicketPurchase, submitReviewed, type TransactionReview as Review } from './web3/transactions';
export default function App() {
  const [selected,setSelected]=useState<ChainKey>('polygon'); const [wallet,setWallet]=useState<WalletState>({connected:false,connecting:false}); const [snapshot,setSnapshot]=useState<LotterySnapshot>({}); const [numbers,setNumbers]=useState<number[]>([]); const [status,setStatus]=useState('Select a verified network to view live on-chain data.'); const [review,setReview]=useState<Review>(); const [busy,setBusy]=useState(false);
  const controller=useMemo(()=>new WalletController(setWallet),[]); const chain=CHAINS[selected];
  useEffect(()=>{controller.reconnect().catch(()=>undefined);},[controller]); useEffect(()=>{setSnapshot({});readLottery(chain).then(s=>{setSnapshot(s);setStatus('Live contract data');}).catch(e=>setStatus(e.message));},[chain]);
  const connect=async()=>{try{await controller.connect();}catch(e){setWallet({connected:false,connecting:false,error:friendlyError(e)});}};
  const reviewTicket=async()=>{try{const ticket=normalizeTicketNumbers(numbers);if(chain.contracts.status!=='verified')return void setStatus(chain.contracts.note??'Verification Required.');if(!wallet.connected)return void setStatus('Connect a wallet before reviewing a ticket.');if(wallet.chainId!==chain.chainId)return void setStatus(`Switch your wallet to ${chain.name}.`);setReview(await prepareTicketPurchase(chain,controller.getProvider(),ticket));}catch(e){setStatus(friendlyError(e));}};
  const confirm=async()=>{if(!review||!controller.getProvider())return;try{setBusy(true);const receipt=await submitReviewed(controller.getProvider()!,review.request);setStatus(review.kind==='approval'?`USDT approval confirmed in block ${receipt?.blockNumber??'pending'}. Review the ticket transaction next.`:`Ticket confirmed in block ${receipt?.blockNumber??'pending'}.`);setReview(undefined);if(review.kind==='ticket')setNumbers([]);}catch(e){setStatus(friendlyError(e));}finally{setBusy(false);}};
  const activeChain=chainById(wallet.chainId);
  return <main><nav><a className="brand" href="#top">MEGA<span>CRYPTO</span><i>V2</i></a><div className="nav-status"><span className={wallet.connected?'dot live':'dot'}/>{wallet.connected?`${wallet.address!.slice(0,6)}…${wallet.address!.slice(-4)}`:'Not connected'}<button onClick={connect} disabled={wallet.connecting}>{wallet.connecting?'Connecting…':wallet.connected?'Wallet connected':'Connect wallet'}</button></div></nav><header id="top" className="hero"><div><p className="eyebrow">DECENTRALIZED • TRANSPARENT • MULTI-CHAIN</p><h1>Luck, with<br/><em>proof.</em></h1><p className="lede">Select your numbers, verify every detail, and decide in your own wallet.</p><div className="hero-actions"><button disabled={numbers.length!==15} onClick={reviewTicket}>Review ticket <span>→</span></button><a href="#fairness">How fairness works</a></div></div><aside className="jackpot"><p>Current jackpot</p><strong>{displayToken(snapshot.jackpot,chain.contracts.tokenDecimals)}</strong><span>{chain.contracts.tokenSymbol} {snapshot.jackpot===undefined?'• unavailable':'• live'}</span><hr/><div><small>Selection</small><b>{numbers.length} / 15</b></div><div><small>Ticket price</small><b>{displayToken(snapshot.ticketPrice,chain.contracts.tokenDecimals)} USDT</b></div></aside></header><p className="status" role="status">{status}{wallet.connected&&activeChain&&activeChain.key!==selected?` · Wallet is on ${activeChain.name}`:''}</p><NumberPicker value={numbers} onChange={setNumbers}/><NetworkGrid selected={selected} onSelect={setSelected}/><section className="cards"><article className="panel"><p className="eyebrow">YOUR POSITION</p><h2>Tickets & rewards</h2><p className="empty">Connect a wallet to read your verified ticket and reward state.</p></article><article className="panel"><p className="eyebrow">DRAW HISTORY</p><h2>Public, not simulated</h2><p className="empty">Historic rounds are only shown from bounded on-chain event queries.</p></article></section><div id="fairness"><Fairness/></div><footer>© 2026 MegaCrypto Lottery · This app never asks for a recovery phrase or private key.</footer>{review&&<TransactionReview review={review} onCancel={()=>setReview(undefined)} onConfirm={confirm} busy={busy}/>}</main>;
}

